-- Migration 118: enrichissement de la base de connaissances de l'agent IA.
-- Couvre tous les flux métier que l'agent doit savoir expliquer/manipuler en consultation
-- (activités, labos, gérants, fournisseurs, abonnement, ventes, articles vendables,
-- prestataires, suppléments, catégories, produits transformés, modes de prix, timbre fiscal,
-- rapports, référentiel, charges fixes). Titres distincts des 14 entrées de la migration 115.
INSERT INTO ai_knowledge_base (titre, contenu, mots_cles, categorie) VALUES
('Activité (point de vente)',
 $$Une activité est un point de vente du client (restaurant, café, kiosque…). Elle a son propre stock, ses approvisionnements, ses ventes et ses pertes. Un compte entreprise peut avoir plusieurs activités ; un compte indépendant en a une seule. Les données peuvent être filtrées par activité.$$,
 $$activite, activites, point de vente, restaurant, cafe, branche, etablissement, mon entreprise$$, 'structure'),
('Labo central',
 $$Le labo (laboratoire central) est l'unité de production d'une entreprise. Il détient son propre stock d'ingrédients, fabrique des produits transformés (PT) et approvisionne les activités via des transferts. Le stock du labo est distinct du stock des activités.$$,
 $$labo, laboratoire, labo central, production, cuisine centrale, transfert vers activite$$, 'structure'),
('Gérant',
 $$Un gérant est un utilisateur délégué, rattaché au compte d'une entreprise et affecté à une ou plusieurs activités et/ou labos. Il ne voit et ne gère que le périmètre qui lui est assigné. Il consulte/saisit le stock, les appros, les pertes de ses activités/labos.$$,
 $$gerant, gerants, delegue, responsable, affectation, perimetre$$, 'structure'),
('Fournisseur',
 $$Un fournisseur est un partenaire d'approvisionnement de l'entreprise (nom, adresse, téléphone). Chaque ligne d'appro peut être rattachée à un fournisseur et à une référence de facture. Les fournisseurs sont partagés au niveau de l'entreprise et affectables aux activités.$$,
 $$fournisseur, fournisseurs, achat, appro, facture, partenaire$$, 'concept'),
('Abonnement et capacité',
 $$L'abonnement définit la capacité souscrite du client : nombre d'activités, de labos et de gérants, plus le forfait mensuel et l'onboarding. Le mode du compte (actif, lecture seule, désactivé) dépend du paiement. Augmenter la capacité se fait via une demande de supplément (avenant).$$,
 $$abonnement, plan, capacite, forfait, mensuel, nb activites, nb labos, nb gerants, paiement, mode compte$$, 'concept'),
('Vente',
 $$Une vente est une transaction enregistrée sur une activité, à une date, avec un statut (confirmée/annulée) et un canal : directe (sur place) ou via un prestataire de livraison. Chaque vente contient des lignes (article vendu, quantité, prix de vente, coût matière unitaire). Le chiffre d'affaires (CA) est la somme des prix de vente.$$,
 $$vente, ventes, ca, chiffre affaires, ticket, transaction, encaissement, vendu$$, 'concept'),
('Article vendable',
 $$Un article vendable est un produit ou un article configuré à la vente sur une activité, avec un prix de vente et un statut actif. Il peut s'agir d'une fiche technique (produit) ou d'un article valorisé. Les prix de vente sont historisés à chaque modification.$$,
 $$article vendable, vendable, prix de vente, catalogue, carte, menu, configuration vente$$, 'concept'),
('Prestataire de livraison',
 $$Un prestataire de livraison (ex : Uber Eats, Talabat, Glovo) est une plateforme tierce via laquelle des ventes sont réalisées, avec une commission en pourcentage. Les prestataires sont activés au niveau de l'entreprise et le canal de vente "prestataire" s'oppose à la vente "directe".$$,
 $$prestataire, livraison, uber eats, talabat, glovo, commission, plateforme, canal$$, 'concept'),
('Supplément',
 $$Un supplément est un produit vendu en plus d'un produit principal et facturé séparément (ex : sauce, extra fromage). Il a sa propre catégorie de type "supplément" et entre dans le calcul du chiffre d'affaires.$$,
 $$supplement, supplements, extra, ajout, option, accompagnement$$, 'concept'),
('Catégorie de produit',
 $$Les catégories de produit classent les produits vendables, distinctes des catégories d'articles. Elles sont typées : vendable, supplément ou valorisé. La catégorie est obligatoire à la création d'un produit vendable ou d'un supplément et sert au regroupement dans la saisie de vente et les rapports.$$,
 $$categorie de produit, categorie produit, classement, type produit, vendable, supplement, valorise$$, 'concept'),
('Famille et catégorie d''article',
 $$Le référentiel articles est organisé en deux niveaux : la famille (niveau 1, ex : Fruits, Légumes, Viandes) puis la catégorie (niveau 2 sous la famille). Chaque article appartient à une catégorie. Cette arborescence sert au filtrage et aux regroupements.$$,
 $$famille, familles, categorie article, classification, arborescence, regroupement$$, 'concept'),
('Unité de mesure',
 $$Chaque article a une unité de mesure (kg, L, pièce, g…) utilisée pour le stock, les portions des fiches techniques et les prix unitaires. Les unités sont propres à chaque client.$$,
 $$unite, unites, mesure, kg, litre, piece, gramme$$, 'concept'),
('Produit transformé (PT)',
 $$Un produit transformé (PT) est fabriqué au labo à partir d'une recette d'ingrédients. Sa production déduit automatiquement les ingrédients du stock du labo et crée un stock de PT, valorisé au coût calculé de la recette. Les PT peuvent ensuite être transférés ou utilisés.$$,
 $$produit transforme, pt, fabrication, production labo, recette, transformation$$, 'process'),
('Mode de prix d''une fiche technique',
 $$Le coût d'une fiche technique peut être calculé selon plusieurs modes de prix des ingrédients : prix moyen du stock à une date, prix manuel saisi, prix historique, ou mixte. Cela permet de simuler le coût de revient selon différents scénarios d'achat.$$,
 $$mode de prix, prix moyen, prix manuel, prix historique, simulation, cout de revient, fiche technique$$, 'concept'),
('Timbre fiscal',
 $$Le timbre fiscal est une taxe fixe (1 DT en Tunisie) ajoutée au montant TTC d'une facture lorsqu'il s'applique. Il est suivi par LabFlow sur les factures d'approvisionnement.$$,
 $$timbre fiscal, timbre, taxe facture, 1 dt$$, 'concept'),
('Rapport (Excel / PDF)',
 $$L'agent peut générer et envoyer par email un rapport Excel ou PDF récapitulant le stock, les pertes, les inventaires et les transferts du client. Le client peut le demander explicitement (ex : « envoie-moi le rapport Excel ») et l'agent peut aussi proposer de l'envoyer par email.$$,
 $$rapport, rapports, excel, pdf, export, envoyer par email, recapitulatif$$, 'process'),
('Référentiel articles',
 $$Le référentiel regroupe les articles/ingrédients du client avec leur unité, leur famille/catégorie et leur prix de référence. C'est la base à partir de laquelle on construit le stock, les fiches techniques et les ventes.$$,
 $$referentiel, articles, ingredients, catalogue articles, liste articles, base$$, 'concept'),
('Charges fixes',
 $$Les charges fixes d'une activité (loyer, charges de personnel, électricité/gaz, eau…) sont saisies soit en montant global, soit en détail. Elles servent au calcul de la rentabilité au-delà du coût matière.$$,
 $$charges fixes, charges, loyer, personnel, electricite, eau, frais fixes, rentabilite$$, 'concept')
ON CONFLICT (lower(titre)) DO NOTHING;
